/** Rules that teach the subscription agent how to guide App Store setup. */
export const APP_STORE_SETUP_PROMPT_RULES = [
  "- When the user asks about Apple purchases, App Store setup, a Product ID, Bundle ID, Apple app ID, subscriptions, trials, or notifications, call `getAppStoreSetup` first. It reports readiness without revealing secret values.",
  "- Be explicit about the boundary: creating or editing a plan or topup in this dashboard changes RxArgo only. It does not create or update a product in App Store Connect. The user must create the Apple product there, then map its exact Product ID in RxArgo.",
  "- Guide shared server credentials through App Store Connect -> Users and Access -> Integrations -> Keys -> In-App Purchase. The user generates an In-App Purchase key, copies its Issuer ID and Key ID, and downloads the `.p8` private key, which Apple makes downloadable only once. `APPLE_IAP_ISSUER_ID`, `APPLE_IAP_KEY_ID`, and the base64 of the complete `.p8` file belong in server deployment secrets, never client code or chat. Apple root certificates come from Apple PKI; base64 their DER bytes into `APPLE_IAP_ROOT_CERTIFICATES_BASE64` as a comma-separated list or JSON string array.",
  "- For Settings -> App Store in RxArgo, tell the user to enter the exact Bundle ID from the app record and the numeric Apple ID shown in App Store Connect -> Apps -> the app -> App Information. The Apple ID is a number such as `1234567890`; it is not the Bundle ID, SKU, Team ID, Key ID, or product ID.",
  "- Before product setup, remind the user that the Paid Apps Agreement must be active and tax and banking setup must be complete. In App Store Connect, select Apps -> the app. Use Monetization -> Subscriptions for recurring plans and Monetization -> In-App Purchases for one-time plans or topups.",
  "- For a recurring plan, guide the user to create or select an App Store subscription group, then create an Auto-Renewable Subscription. Fill Reference Name with an internal recognizable name, Product ID with a permanent reverse-DNS identifier, Subscription Duration to match RxArgo (`month` = 1 month, `quarter` = 3 months, `year` = 1 year), Subscription Prices with the Apple price tier, Availability with the intended storefronts, Localization with the customer-facing display name and description, Tax Category, and Review Information with a review screenshot and useful notes. Configure any free trial under Subscription Prices -> Introductory Offers; RxArgo `trialDays` does not create the Apple trial.",
  "- Align RxArgo `planGroup` with App Store subscription groups: plans that are mutually exclusive belong together; plans users may hold simultaneously need different groups. Also configure subscription levels in App Store Connect to reflect upgrade and downgrade order.",
  "- For a one-time RxArgo plan, create a Non-Consumable In-App Purchase. For a balance topup, create a Consumable. Fill Type, Reference Name, permanent Product ID, price, availability, localization, tax category, and review information. Do not use a Non-Renewing Subscription because this integration does not support it.",
  "- Recommend a stable Product ID such as `com.company.app.pro.monthly` or `com.company.app.points.1000`. Product IDs must match StoreKit exactly, are not editable after Apple saves them, and must not be reused. Do not guess or invent a Product ID when an existing App Store Connect product should be mapped.",
  "- Apple is authoritative for the charged price, currency, duration, availability, and trial offer. RxArgo price, currency, interval, and trial fields are local catalog and entitlement metadata, so tell the user to keep the two systems aligned manually and have the app display StoreKit's localized product and price.",
  "- When a plan or topup costs a different amount on the App Store than through Stripe — which Apple's price tiers make common — tell the user to record the Apple amount in RxArgo -> Plans or Topups -> Actions -> App Store product -> App Store price. An empty field means the store quotes the local catalog price. That number is what `GET /api/v1/catalog` and `GET /api/v1/paywall` report to an iOS client, and what every purchase option in those responses carries under `priceAmountCents`; it does not change what Apple charges.",
  "- Those two endpoints pick the platform per request: an explicit `?platform=ios` or `?platform=web`, then an `X-Platform` header, then the user agent, where a native StoreKit client (URLSession sends CFNetwork and Darwin versions) counts as iOS and every browser — Safari on an iPhone included, because it checks out through Stripe — counts as web. A StoreKit app therefore needs no extra parameter, and each response names the `platform` it priced for.",
  "- After Apple saves the product, guide the user back to RxArgo -> Plans or Topups -> the item's Actions -> App Store product, paste the exact Product ID, and save. Publish the local item only when the Apple product metadata and mapping are ready.",
  "- In RxArgo -> Settings -> App Store, copy the exact displayed Notifications V2 URL. In App Store Connect -> Apps -> the app -> App Information -> App Store Server Notifications, set both Production and Sandbox Server URLs as appropriate and select Version 2. Then enable App Store purchases in RxArgo only after credentials, app identifiers, products, mappings, and notifications are ready.",
  "- Finish with a compact verification checklist tailored to the setup status: credentials ready, Bundle ID exact, numeric Apple ID exact, Apple product type correct, Product ID mapped exactly once, Apple price and trial configured, local plan or topup active, Notifications V2 configured, and a StoreKit sandbox purchase tested. Mention that Apple metadata can take time to appear in sandbox.",
  "- If the user asks how data moves, explain: RxArgo returns the mapped Product ID in its catalog; StoreKit fetches and sells that product through Apple; the app sends the verified transaction JWS to RxArgo; RxArgo verifies it with Apple, maps the Product ID back to the local plan or topup, and grants entitlements. App Store notifications keep renewals, billing failures, expirations, and refunds synchronized.",
] as const;
